ALTER TABLE jobs ADD COLUMN matched_skills JSON NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN missing_skills JSON NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN matched_tools JSON NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN missing_tools JSON NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN experience_gap FLOAT NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN score_breakdown_json JSON NOT NULL DEFAULT '{}';
